kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-location-volume
  labels:
    type: local
    app: postgres-location
spec:
  storageClassName: manual
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-location-pv-claim
  labels:
    app: postgres-location
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-location
  labels:
    app: postgres-location
spec:
  type: NodePort
  selector:
    app: postgres-location
  ports:
   - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-location
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-location
  template:
    metadata:
      labels:
        app: postgres-location
    spec:
      containers:
        - name: postgres-location
          image: postgis/postgis:12-2.5-alpine
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: db-location
                key: DB_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: location-db-secret
                key: DB_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: db-location
                key: DB_NAME
          volumeMounts:
            - mountPath: /var/lib/locationdb/data
              name: location-db
      volumes:
        - name: location-db
          persistentVolumeClaim:
            claimName: postgres-location-pv-claim
