apiVersion: v1
kind: Service
metadata:
  labels:
    service: location-grpc
  name: location-grpc
spec:
  ports:
  - name: "5005"
    port: 5005
    targetPort: 5005
    nodePort: 30004
  selector:
    service: location-grpc
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-grpc
  name: location-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-grpc
  template:
    metadata:
      labels:
        service: location-grpc
    spec:
      containers:
      - image: luizvellozo/udaconnect-location-grpc:latest
        name: location-grpc
        imagePullPolicy: Always
        env:
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_URL
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_TOPIC
      restartPolicy: Always